[build]
  publish = "dist/public"
  command = "npm run build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
# Optional: If you have API routes
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
